<?xml version="1.0" encoding="utf-8"?><Database Name="dbKnow" Class="DBMap" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\dbKnow.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.trn_Tables" Member="trn_Tables">
    <Type Name="trn_Table">
      <Column Name="TableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatabaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastScanned" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LockNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="trn_Table_trn_Field" Member="trn_Fields" ThisKey="TableID" OtherKey="TableID" Type="trn_Field" />
      <Association Name="trn_Database_trn_Table" Member="trn_Database" ThisKey="DatabaseID" OtherKey="DatabaseID" Type="trn_Database" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.trn_Databases" Member="trn_Databases">
    <Type Name="trn_Database">
      <Column Name="DatabaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DatabaseTypeInd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConnectionString" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastScanned" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LockNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="trn_Database_trn_Table" Member="trn_Tables" ThisKey="DatabaseID" OtherKey="DatabaseID" Type="trn_Table" />
    </Type>
  </Table>
  <Table Name="dbo.trn_Fields" Member="trn_Fields">
    <Type Name="trn_Field">
      <Column Name="FieldID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nullable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FieldType" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastScanned" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LockNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="trn_Table_trn_Field" Member="trn_Table" ThisKey="TableID" OtherKey="TableID" Type="trn_Table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>